// Covariate name mapping from Excel to existing covariate names
// Generated from imputation-appendix-file-for-snf-effective-10-01-2024.xlsx

export const covariateMapping = {
  "≤54 Years": "≤54 Years",
  ">90 Years": ">90 Years",
  "Primary Medical Condition Category: Stroke": "Primary Medical Condition Category: Stroke",
  "Primary Medical Condition Category: Non-Traumatic Brain Dysfunction and Traumatic Brain Dysfunction": "Primary Medical Condition Category: Non-Traumatic Brain Dysfunction and Traumatic Brain Dysfunction",
  "Primary Medical Condition Category: Non-Traumatic Spinal Cord Dysfunction": "Primary Medical Condition Category: Non-Traumatic Spinal Cord Dysfunction",
  "Primary Medical Condition Category: Traumatic Spinal Cord Dysfunction": "Primary Medical Condition Category: Traumatic Spinal Cord Dysfunction",
  "Primary Medical Condition Category: Progressive Neurological Conditions": "Primary Medical Condition Category: Progressive Neurological Conditions",
  "Primary Medical Condition Category: Other Neurological Conditions": "Primary Medical Condition Category: Other Neurological Conditions",
  "Primary Medical Condition Category: Fractures and Other Multiple Trauma": "Primary Medical Condition Category: Fractures and Other Multiple Trauma",
  "Primary Medical Condition Category: Amputation": "Primary Medical Condition Category: Amputation",
  "Primary Medical Condition Category: Other Orthopedic Conditions": "Primary Medical Condition Category: Other Orthopedic Conditions",
  "Primary Medical Condition Category: Medically Complex Conditions": "Primary Medical Condition Category: Medically Complex Conditions",
  "Prior Surgery": "Prior Surgery",
  "Prior Functioning, Self-Care: Dependent": "Prior Functioning, Self-Care: Dependent",
  "Prior Functioning, Self-Care: Some Help": "Prior Functioning, Self-Care: Some Help",
  "Prior Functioning, Indoor Mobility (Ambulation): Dependent": "Prior Functioning, Indoor Mobility (Ambulation): Dependent",
  "Prior Functioning, Indoor Mobility (Ambulation): Some Help": "Prior Functioning, Indoor Mobility (Ambulation): Some Help",
  "Prior Functioning, Stairs: Dependent": "Prior Functioning, Stairs: Dependent",
  "Prior Functioning, Stairs: Some Help": "Prior Functioning, Stairs: Some Help",
  "Prior Functioning, Functional Cognition: Dependent": "Prior Functioning, Functional Cognition: Dependent",
  "Prior Mobility Device Use: Walker": "Prior Mobility Device Use: Walker",
  "Prior Mobility Device Use: Manual Wheelchair and/or Motorized Wheelchair and/or Scooter": "Prior Mobility Device Use: Manual Wheelchair and/or Motorized Wheelchair and/or Scooter",
  "Prior Mobility Device Use: Mechanical Lift": "Prior Mobility Device Use: Mechanical Lift",
  "Prior Mobility Device Use: Orthotics/Prosthetics": "Prior Mobility Device Use: Orthotics/Prosthetics",
  "High BMI": "High BMI",
  "Low BMI": "Low BMI",
  "Septicemia, Sepsis, Systemic Inflammatory Response Syndrome/Shock (HCC2)": "Septicemia, Sepsis, Systemic Inflammatory Response Syndrome/Shock (HCC2)",
  "Metastatic Cancer and Acute Leukemia (HCC8)": "Metastatic Cancer and Acute Leukemia (HCC8)",
  "Lymphoma and Other Cancers (HCC10)": "Lymphoma and Other Cancers (HCC10)",
  "Colorectal, Bladder, and Other Cancers (HCC11)": "Colorectal, Bladder, and Other Cancers (HCC11)",
  "Diabetes: Diabetes With Chronic Complications (HCC18) or Diabetes Without Complications (HCC19)": "Diabetes: Diabetes With Chronic Complications (HCC18) or Diabetes Without Complications (HCC19)",
  "Other Significant Endocrine and Metabolic Disorders (HCC23)": "Other Significant Endocrine and Metabolic Disorders (HCC23)",
  "Intestinal Obstruction/Perforation (HCC33)": "Intestinal Obstruction/Perforation (HCC33)",
  "Dementia: Dementia With Complications (HCC51), Dementia Without Complications (HCC52)": "Dementia: Dementia With Complications (HCC51), Dementia Without Complications (HCC52)",
  "Mental Health Disorders: Schizophrenia (HCC57), Major Depressive, Bipolar, and Paranoid Disorders (HCC59), Reactive and Unspecified Psychosis (HCC58), Personality Disorders (HCC60)": "Mental Health Disorders: Schizophrenia (HCC57), Major Depressive, Bipolar, and Paranoid Disorders (HCC59), Reactive and Unspecified Psychosis (HCC58), Personality Disorders (HCC60)",
  "Tetraplegia (Excluding Complete Tetraplegia) (HCC70) and Paraplegia (HCC71)": "Tetraplegia (Excluding Complete Tetraplegia) (HCC70) and Paraplegia (HCC71)",
  "Multiple Sclerosis (HCC77)": "Multiple Sclerosis (HCC77)",
  "Angina Pectoris (HCC88)": "Angina Pectoris (HCC88)",
  "Hemiplegia/Hemiparesis (HCC103)": "Hemiplegia/Hemiparesis (HCC103)",
  "Aspiration, Bacterial, and Other Pneumonias: Aspiration and Specified Bacterial Pneumonias (HCC114), Pneumococcal Pneumonia, Empyema, Lung Abscess (HCC115)": "Aspiration, Bacterial, and Other Pneumonias: Aspiration and Specified Bacterial Pneumonias (HCC114), Pneumococcal Pneumonia, Empyema, Lung Abscess (HCC115)",
  "Dialysis Status (HCC134), Chronic Kidney Disease, Stage 5 (HCC136)": "Dialysis Status (HCC134), Chronic Kidney Disease, Stage 5 (HCC136)",
  "Chronic Kidney Disease - Stages 1-4, Unspecified: Chronic Kidney Disease, Severe (Stage 4) (HCC137), Chronic Kidney Disease, Moderate (Stage 3) (HCC138), Chronic Kidney Disease, Mild or Unspecified (Stages 1-2 or Unspecified) (HCC139)": "Chronic Kidney Disease - Stages 1-4, Unspecified: Chronic Kidney Disease, Severe (Stage 4) (HCC137), Chronic Kidney Disease, Moderate (Stage 3) (HCC138), Chronic Kidney Disease, Mild or Unspecified (Stages 1-2 or Unspecified) (HCC139)",
  "Major Head Injury (HCC167)": "Major Head Injury (HCC167)",
  "Amputations: Traumatic Amputations and Complications (HCC173), Amputation Status, Lower Limb/Amputation Complications (HCC189), Amputation Status, Lower Limb/ Amputation Complications (HCC189)": "Amputations: Traumatic Amputations and Complications (HCC173), Amputation Status, Lower Limb/Amputation Complications (HCC189), Amputation Status, Lower Limb/ Amputation Complications (HCC189)",
  "55–64 Years": "55-64 Years",
  "75–84 Years": "75-84 Years",
  "85–90 Years": "85-90 Years",
  "Primary Medical Condition Category: Debility, Cardiorespiratory Conditions ": "Primary Medical Condition Category: Debility, Cardiorespiratory Conditions",
  "No Physical or Occupational Therapy – Admission": "No Physical or Occupational Therapy - Admission",
  "Stage 2 Pressure Ulcer – Admission": "Stage 2 Pressure Ulcer - Admission",
  "Stage 3, 4 or Unstageable Pressure Ulcer/Injury – Admission": "Stage 3, 4 or Unstageable Pressure Ulcer/Injury - Admission",
  "Cognitive Function, BIMS Score: Moderately Impaired – Admission": "Cognitive Function, BIMS Score: Moderately Impaired - Admission",
  "Cognitive Function, BIMS Score: Severely Impaired – Admission": "Cognitive Function, BIMS Score: Severely Impaired - Admission",
  "Communication Impairment: Moderate to Severe – Admission": "Communication Impairment: Moderate to Severe - Admission",
  "Communication Impairment: Mild – Admission": "Communication Impairment: Mild - Admission",
  "Urinary Continence: Occasionally Incontinent, Frequently Incontinent, or Always Incontinent – Admission": "Urinary Continence: Occasionally Incontinent, Frequently Incontinent, or Always Incontinent - Admission",
  "Urinary Continence: Not Rated (Indwelling Urinary Catheter) – Admission": "Urinary Continence: Not Rated (Indwelling Urinary Catheter) - Admission",
  "Bowel Continence: Occasionally Incontinent, Frequently Incontinent – Admission": "Bowel Continence: Occasionally Incontinent, Frequently Incontinent - Admission",
  "Bowel Continence: Always Incontinent – Admission": "Bowel Continence: Always Incontinent - Admission",
  "History of Falls – Admission": "History of Falls - Admission",
  "Nutritional Approaches: Mechanically Altered Diet – Admission": "Nutritional Approaches: Mechanically Altered Diet - Admission",
  "Total Parenteral/IV Feeding or Tube Feeding: While a Resident – Admission": "Total Parenteral/IV Feeding or Tube Feeding: While a Resident - Admission"
};

// Unmapped covariates that need manual review
export const unmappedCovariates = [
  "Parkinson’s and Huntington’s Diseases (HCC78)",
  "Uses Wheelchair",
  "Eating (GG0130A1) - Valid Score",
  "Eating (GG0130A1) - Not Attempted",
  "Oral Hygiene (GG0130B1) - Valid Score",
  "Oral Hygiene (GG0130B1) - Not Attempted",
  "Toileting Hygiene (GG0130C1) - Valid Score",
  "Toileting Hygiene (GG0130C1) - Not Attempted",
  "Shower/Bathe Self (GG0130E1) - Valid Score",
  "Shower/Bathe Self (GG0130E1) - Not Attempted",
  "Upper Body Dressing (GG0130F1) - Valid Score",
  "Upper Body Dressing (GG0130F1) - Not Attempted",
  "Lower Body Dressing (GG0130G1) - Valid Score",
  "Lower Body Dressing (GG0130G1) - Not Attempted",
  "Put on/Take off Footwear (GG0130H1) - Valid Score",
  "Put on/Take off Footwear (GG0130H1) - Not Attempted",
  "Roll Left and Right (GG0170A1) - Valid Score",
  "Roll Left and Right (GG0170A1) - Not Attempted",
  "Sit to Lying (GG0170B1) - Valid Score",
  "Sit to Lying (GG0170B1) - Not Attempted",
  "Lying to Sitting on Side of Bed (GG0170C1) - Valid Score",
  "Lying to Sitting on Side of Bed (GG0170C1) - Not Attempted",
  "Sit to Stand (GG0170D1) - Valid Score",
  "Sit to Stand (GG0170D1) - Not Attempted",
  "Chair/Bed-to-Chair Transfer (GG0170E1) - Valid Score",
  "Chair/Bed-to-Chair Transfer (GG0170E1) - Not Attempted",
  "Toilet Transfer (GG0170F1) - Valid Score",
  "Toilet Transfer (GG0170F1) - Not Attempted",
  "Car Transfer (GG0170G1) - Valid Score",
  "Car Transfer (GG0170G1) - Not Attempted",
  "Walk 10 Feet (GG0170I1) - Valid Score",
  "Walk 10 Feet (GG0170I1) - Not Attempted",
  "Walk 50 Feet With 2 Turns (GG0170J1) - Valid Score",
  "Walk 50 Feet With 2 Turns (GG0170J1) - Not Attempted",
  "Walk 50 Feet With 2 Turns (GG0170J1) - Skipped",
  "Walk 150 Feet (GG0170K1) - Valid Score",
  "Walk 150 Feet (GG0170K1) - Not Attempted",
  "Walk 150 Feet (GG0170K1) - Skipped",
  "Walk 10 Feet Uneven Surface (GG0170L1) - Valid Score",
  "Walk 10 Feet Uneven Surface (GG0170L1) - Not Attempted",
  "Walk 10 Feet Uneven Surface (GG0170L1) - Skipped",
  "1 Step (curb) (GG0170M1) - Valid Score",
  "1 Step (curb) (GG0170M1) - Not Attempted",
  "4 Steps (GG0170N1) - Valid Score",
  "4 Steps (GG0170N1) - Not Attempted",
  "4 Steps (GG0170N1) - Skipped",
  "12 Steps (GG0170O1) - Valid Score",
  "12 Steps (GG0170O1) - Not Attempted",
  "12 Steps (GG0170O1) - Skipped",
  "Picking up Object (GG0170P1) - Valid Score",
  "Picking up Object (GG0170P1) - Not Attempted",
  "Wheel 50 Feet With 2 Turns (GG0170R1) - Valid Score",
  "Wheel 50 Feet With 2 Turns (GG0170R1) - Not Attempted",
  "Wheel 50 Feet With 2 Turns (GG0170R1) - Skipped",
  "Wheel 150 Feet (GG0170S1) - Valid Score",
  "Wheel 150 Feet (GG0170S1) - Not Attempted",
  "Wheel 150 Feet (GG0170S1) - Skipped",
  "End of worksheet"
];

// Summary
export const mappingSummary = {
  totalImputationCovariates: 120,
  successfullyMapped: 62,
  unmappedCount: 58,
  mappingRate: 51.7%
};
