export const functionMultipliers = {
  "55-64 Years": 0.0743,
  "65-74 Years": 0.0,
  "75-84 Years": -0.3451,
  "85-90 Years": -0.8555,
  ">90 Years": -1.6377,
  "Admission Function - Continuous Form": 1.0425,
  "Admission Function - Squared Form": -0.0091,
  "Amputations: Traumatic Amputations and Complications (HCC173), Amputation Status, Lower Limb/Amputation Complications (HCC189), Amputation Status, Lower Limb/ Amputation Complications (HCC189)": -0.718,
  "Angina Pectoris (HCC88)": 0.1939,
  "Aspiration, Bacterial, and Other Pneumonias: Aspiration and Specified Bacterial Pneumonias (HCC114), Pneumococcal Pneumonia, Empyema, Lung Abscess (HCC115)": -0.0267,
  "Bowel Continence: Always Incontinent - Admission": -4.3787,
  "Bowel Continence: Occasionally Incontinent, Frequently Incontinent - Admission": -1.1636,
  "Chronic Kidney Disease - Stages 1-4, Unspecified: Chronic Kidney Disease, Severe (Stage 4) (HCC137), Chronic Kidney Disease, Moderate (Stage 3) (HCC138), Chronic Kidney Disease, Mild or Unspecified (Stages 1-2 or Unspecified) (HCC139)": -0.1089,
  "Cognitive Function, BIMS Score: Moderately Impaired - Admission": -1.2709,
  "Cognitive Function, BIMS Score: Severely Impaired - Admission": -2.5276,
  "Colorectal, Bladder, and Other Cancers (HCC11)": 0.1316,
  "Communication Impairment: Mild - Admission": -0.5816,
  "Communication Impairment: Moderate to Severe - Admission": -1.294,
  "Dementia: Dementia With Complications (HCC51), Dementia Without Complications (HCC52)": -0.7607,
  "Diabetes: Diabetes With Chronic Complications (HCC18) or Diabetes Without Complications (HCC19)": -0.1949,
  "Dialysis Status (HCC134), Chronic Kidney Disease, Stage 5 (HCC136)": -1.2601,
  "Hemiplegia/Hemiparesis (HCC103)": -1.735,
  "High BMI": -1.5846,
  "History of Falls - Admission": 0.4549,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Amputation": 0.1654,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Debility, Cardiorespiratory Conditions": 0.1772,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Fractures and Other Multiple Trauma": 0.0476,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Hip and Knee Replacements": 0.0,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Medically Complex Conditions": 0.1793,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Non-Traumatic Brain Dysfunction and Traumatic Brain Dysfunction": 0.1644,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Non-Traumatic Spinal Cord Dysfunction": 0.1627,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Other Neurological Conditions": 0.1485,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Other Orthopedic Conditions": 0.1077,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Progressive Neurological Conditions": 0.1631,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Stroke": 0.215,
  "Interaction of Admission Function Score and Primary Medical Condition Category: Traumatic Spinal Cord Dysfunction": 0.3309,
  "Intestinal Obstruction/Perforation (HCC33)": 0.3063,
  "Low BMI": -0.3545,
  "Lymphoma and Other Cancers (HCC10)": -0.7845,
  "Major Head Injury (HCC167)": 0.2196,
  "Mental Health Disorders: Schizophrenia (HCC57), Major Depressive, Bipolar, and Paranoid Disorders (HCC59), Reactive and Unspecified Psychosis (HCC58), Personality Disorders (HCC60)": -0.3707,
  "Metastatic Cancer and Acute Leukemia (HCC8)": -0.7201,
  "Model Intercept": 30.0118,
  "Multiple Sclerosis (HCC77)": -1.5428,
  "No Physical or Occupational Therapy - Admission": -4.0674,
  "Nutritional Approaches: Mechanically Altered Diet - Admission": -0.7066,
  "Other Significant Endocrine and Metabolic Disorders (HCC23)": 0.1824,
  "Parkinson's and Huntington's Diseases (HCC78)": -0.7805,
  "Primary Medical Condition Category: Amputation": -8.3109,
  "Primary Medical Condition Category: Debility, Cardiorespiratory Conditions": -8.0956,
  "Primary Medical Condition Category: Fractures and Other Multiple Trauma": -2.9722,
  "Primary Medical Condition Category: Hip and Knee Replacements": 0.0,
  "Primary Medical Condition Category: Medically Complex Conditions": -8.0534,
  "Primary Medical Condition Category: Non-Traumatic Brain Dysfunction and Traumatic Brain Dysfunction": -7.6338,
  "Primary Medical Condition Category: Non-Traumatic Spinal Cord Dysfunction": -7.5056,
  "Primary Medical Condition Category: Other Neurological Conditions": -6.8022,
  "Primary Medical Condition Category: Other Orthopedic Conditions": -5.1916,
  "Primary Medical Condition Category: Progressive Neurological Conditions": -8.5182,
  "Primary Medical Condition Category: Stroke": -9.403,
  "Primary Medical Condition Category: Traumatic Spinal Cord Dysfunction": -14.2713,
  "Prior Functioning, Functional Cognition: Dependent": -0.6703,
  "Prior Functioning, Indoor Mobility (Ambulation): Dependent": -1.6296,
  "Prior Functioning, Indoor Mobility (Ambulation): Some Help": -1.0775,
  "Prior Functioning, Self-Care: Dependent": -3.8267,
  "Prior Functioning, Self-Care: Some Help": -2.2614,
  "Prior Functioning, Stairs: Dependent": 0.3419,
  "Prior Functioning, Stairs: Some Help": 0.3431,
  "Prior Mobility Device Use: Manual Wheelchair and/or Motorized Wheelchair and/or Scooter": -2.3343,
  "Prior Mobility Device Use: Mechanical Lift": -3.5764,
  "Prior Mobility Device Use: Orthotics/Prosthetics": 0.104,
  "Prior Mobility Device Use: Walker": 0.0425,
  "Prior Surgery": 0.6576,
  "Septicemia, Sepsis, Systemic Inflammatory Response Syndrome/Shock (HCC2)": 0.3191,
  "Stage 2 Pressure Ulcer - Admission": -0.9505,
  "Stage 3, 4 or Unstageable Pressure Ulcer/Injury - Admission": -1.9886,
  "Tetraplegia (Excluding Complete Tetraplegia) (HCC70) and Paraplegia (HCC71)": -2.8928,
  "Total Parenteral/IV Feeding or Tube Feeding: While a Resident - Admission": -1.1014,
  "Urinary Continence: Not Rated (Indwelling Urinary Catheter) - Admission": -2.1629,
  "Urinary Continence: Occasionally Incontinent, Frequently Incontinent, or Always Incontinent - Admission": -1.0514,
  "≤54 Years": -0.021,
  "Entry": 0.0,
};